name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ReactNET.Server/ReactNET.Server.csproj
      
    - name: Build
      run: dotnet build ReactNET.Server/ReactNET.Server.csproj --no-restore
      
    - name: Test
      run: dotnet test ReactNET.Server/ReactNET.Server.csproj --no-build --verbosity normal
